# Change these first
owner: aniimah # Your GitHub username
repo: uptime-bot # Your GitHub repository name

# Add your sites here
sites:
  
  - name: Bee and Bloom Digital
    url: https://beeandbloom.digital/
  - name: Aborfrah Online
    url: http://aborfrahonline.com/
  - name: Accra Art Center
    url: http://accraartscenter.com/
  - name: Selase Kove-Seyram
    url: https://selasekove.com/
  - name: Insignisncouth
    url: http://insignisncouth.com/
  - name: Heros Animated
    url: http://heroesanimated.com/cgi-sys/suspendedpage.cgi
  - name: Nii Arday Clegg & Co.
    url: http://naclegg.com/
  - name: NAFCO
    url: https://nafco.gov.gh/
  - name: Tiger Eye Foundation
    url: http://tigereyefoundation.org/
  - name: TigerEyePi
    url: https://www.hugedomains.com/domain_profile.cfm?d=tigereyepi&e=com
  - name: Anas Aremeyaw Anas
    url: https://www.hugedomains.com/domain_profile.cfm?d=tigereyepi&e=com
  - name: Cromwell Gray LLP
    url: http://cromwellgray.org/
  - name: My Sars Story
    url: http://mysarsstory.org/
  

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseurl: /uptime-bot
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Bee and Bloom Digital Montoring Bot
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
